### ISSUE TITLE
Requires react-router to use the Select component.

### ISSUE THREAD

**Issue by jameskraus** [catamphetamine/react-responsive-ui#1]
Hey, I wanted to use the Select component, but it seems like a single component cannot be used without (at least) react-router.

Error: 
```
ERROR in ./~/react-responsive-ui/build/menu.js
Module not found: Error: Cannot resolve module 'react-router' in /Users/jameskraus/projects/orgcrmapp/node_modules/react-responsive-ui/build
 @ ./~/react-responsive-ui/build/menu.js 47:19-42
```

My only import statement:
```
import { Select } from 'react-responsive-ui';
```

**Comment by catamphetamine** [comment]
I have rewritten the `<Menu/>` component and removed `react-router` out of it.
Try the latest version.
